# Generated by Django 4.1.2 on 2022-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_label_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CPU', 'CPU'), ('RAM', 'RAM'), ('GPU', 'GPU'), ('none', 'none')], max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('N', '')], max_length=5, null=True),
        ),
    ]
