# Generated by Django 4.1.2 on 2022-11-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_order_orderitem_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CPU', 'Central Processing Unit'), ('RAM', 'Random Access Memory'), ('GPU', 'Graphics Processing Unit')], default='CPU', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='primary', max_length=5),
            preserve_default=False,
        ),
    ]
