# Generated by Django 4.1.2 on 2022-11-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
