# Generated by Django 4.1.2 on 2022-11-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
