# Generated by Django 4.1.2 on 2022-11-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
