# Generated by Django 4.1.2 on 2022-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
