# Generated by Django 4.1.2 on 2022-12-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
