# Generated by Django 4.1.2 on 2022-12-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_comments_image_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image_perfil',
            field=models.ImageField(blank=True, default='profile_image/default.jpg', null=True, upload_to='profile_image/'),
        ),
    ]
